---
- hosts: localhost
  connection: local

  pre_tasks:
    - name: "Update package cache (Fedora)"
      become: true
      changed_when: false
      ansible.builtin.dnf:
        update_cache: true
      when: ansible_distribution == 'Fedora'

- hosts: localhost
  connection: local
  vars:
    git:
      protocol: "ssh"

  roles:
    - workstation
