---
- name: "Add Docker Stable repo (Fedora)"
  become: true
  ansible.builtin.yum_repository:
    name: docker-stable
    description: Docker CE Stable - $basearch
    baseurl: https://download.docker.com/linux/fedora/$releasever/$basearch/stable
    gpgcheck: yes
    gpgkey: https://download.docker.com/linux/fedora/gpg
  when: ansible_distribution == 'Fedora'

- name: "Install docker (Fedora)"
  become: true
  ansible.builtin.dnf:
    name:
      - docker-ce
      - docker-ce-cli
      - containerd.io
      - docker-compose-plugin

- name: "Create docker group"
  become: true
  ansible.builtin.group:
    name: docker
    state: present

- name: "Add current user to docker group"
  become: true
  ansible.builtin.user:
    name: "{{ ansible_user_id }}"
    append: true
    groups:
      - "docker"

- name: "Enable docker.service"
  become: true
  ansible.builtin.systemd:
    name: docker.service
    enabled: true

- name: "Enable containerd.service"
  become: true
  ansible.builtin.systemd:
    name: containerd.service
    enabled: true
