---
- name: "Remove flatpak filter (Fedora)"
  become: true
  ansible.builtin.command:
    cmd: |
      flatpak remote-modify --no-filter flathub
      flatpak update
  when: ansible_distribution == 'Fedora'
