---
- name: "Install fnm"
  ansible.builtin.shell:
    cmd: |
      set -o pipefail
      curl -fsSL https://github.com/Schniz/fnm/raw/master/.ci/install.sh | \
        bash -s -- --skip-shell
    executable: /bin/bash
  args:
    creates: "{{ ansible_user_dir }}/.fnm/fnm"

- name: "Setup zsh (fnm)"
  ansible.builtin.lineinfile:
    name: "{{ ansible_user_dir }}/.zshrc"
    line: '{{ item }}'
    state: present
  with_items:
    - 'export PATH="$HOME/.fnm:$PATH"'
    - 'eval "$(fnm env --use-on-cd)"'
