---
- name: "Install fnm"
  ansible.builtin.shell:
    cmd: |
      set -o pipefail
      curl -fsSL https://github.com/Schniz/fnm/raw/master/.ci/install.sh | \
        bash -s -- --skip-shell
    executable: /bin/bash
  args:
    creates: "{{ ansible_user_dir }}/.fnm/fnm"

- name: "Setup zsh (fnm)"
  ansible.builtin.lineinfile:
    name: "{{ ansible_user_dir }}/.zshenv"
    line: "{{ item }}"
    state: present
  with_items:
    - 'export PATH="$HOME/.fnm:$PATH"'
    - 'eval "$(fnm env --use-on-cd)"'

- name: "Install Node.js LTS (fnm)"
  ansible.builtin.shell:
    cmd: |
      set -o pipefail
      eval "$(fnm env)"
      fnm install --lts
    executable: /bin/bash
  environment:
    PATH: "{{ ansible_user_dir }}/.fnm:{{ ansible_env.PATH }}"
    FNM_DIR: "{{ ansible_user_dir }}/.fnm"
  register: fnm_results
  changed_when: "'successfully downloaded' in fnm_results.stdout"
