---
- name: "Install go"
  become: true
  ansible.builtin.package:
    name: golang

- name: "Setup zsh (go)"
  ansible.builtin.lineinfile:
    name: "{{ ansible_user_dir }}/.zshrc"
    line: 'export PATH="$HOME/go/bin:$PATH"'
    state: present
