---
- name: "Install i3 and its dependencies"
  become: true
  ansible.builtin.package:
    name:
      - i3-gaps
      - polybar
      - rofi
      - picom
      - network-manager-applet
      - blueman
      - xss-lock
      - dex
      - stow
      - scrot
      - feh

- name: "Clone i3 configs"
  vars:
    repo:
      ssh: git@github.com:nicolomaioli/i3.git
      https: https://github.com/nicolomaioli/i3.git
  ansible.builtin.git:
    repo: "{{ repo[git['protocol']] }}"
    dest: "{{ ansible_user_dir }}/Code/i3"
    version: main
    update: yes

- name: "Remove existing i3 directory"
  # Else the following stow will only symlink the `config` file inside it,
  # causing it to appear in the results of `sn` (see tmux conf)
  ansible.builtin.file:
    path: "{{ ansible_user_dir }}/.config/i3"
    state: absent

- name: "Stow i3 configs"
  ansible.builtin.command:
    chdir: "{{ ansible_user_dir }}/Code/i3"
    cmd: "stow --target={{ ansible_user_dir }} {{ item }}"
  with_items:
    - "i3"
    - "dunst"
    - "polybar"
    - "rofi"
    - "picom"
    - "backgrounds"
  when: true
