---
- name: "Configure package manager"
  ansible.builtin.import_tasks: package_manager.yml
  tags: dev

- name: "Install development tools"
  ansible.builtin.import_tasks: devtools.yml
  tags: dev

- name: "Install zsh"
  ansible.builtin.import_tasks: zsh.yml
  tags: dev

- name: "Install fnm"
  ansible.builtin.import_tasks: fnm.yml
  tags: dev

- name: "Install python3"
  ansible.builtin.import_tasks: python3.yml
  tags: dev

- name: "Install go"
  ansible.builtin.import_tasks: go.yml
  tags: dev

- name: "Install deno"
  ansible.builtin.import_tasks: deno.yml
  tags: dev

- name: "Install terraform"
  ansible.builtin.import_tasks: terraform.yml
  tags: dev

- name: "Install fzf"
  ansible.builtin.import_tasks: fzf.yml
  tags: dev

- name: "Install alacritty"
  ansible.builtin.import_tasks: alacritty.yml
  tags: dev

- name: "Install neovim"
  ansible.builtin.import_tasks: neovim.yml
  tags: dev

- name: "Install tmux"
  ansible.builtin.import_tasks: tmux.yml
  tags: dev

- name: "Install aws cli"
  ansible.builtin.import_tasks: awscli.yml
  tags: dev

- name: "Install docker"
  ansible.builtin.import_tasks: docker.yml
  tags: dev

- name: "Add portainer script"
  ansible.builtin.import_tasks: portainer.yml
  tags: dev

- name: "Install Kubernetes tools"
  ansible.builtin.import_tasks: kubernetes.yml
  tags: dev

- name: "Install Google Chrome"
  ansible.builtin.import_tasks: chrome.yml
  tags: dev

- name: "Install Visual Studio Code"
  ansible.builtin.import_tasks: visual_studio_code.yml
  tags: dev

- name: "Remove flatpak filter (Fedora)"
  ansible.builtin.import_tasks: flathub.yml
  tags: dev

- name: "Install Slack"
  ansible.builtin.import_tasks: slack.yml
  tags: dev

- name: "Install i3"
  ansible.builtin.import_tasks: i3.yml
  tags: i3

- name: "Configure X11"
  ansible.builtin.import_tasks: x11.yml
  tags: i3

- name: "Install sway"
  ansible.builtin.import_tasks: sway.yml
  tags: sway

- name: "Copy backgrounds"
  ansible.builtin.import_tasks: backgrounds.yml
  tags:
    - sway
    - i3
