---
- name: "Install development tools"
  ansible.builtin.import_tasks: devtools.yml

- name: "Install zsh"
  ansible.builtin.import_tasks: zsh.yml

- name: "Install fnm"
  ansible.builtin.import_tasks: fnm.yml

- name: "Install node.js"
  ansible.builtin.import_tasks: node_js.yml

- name: "Install python3"
  ansible.builtin.import_tasks: python3.yml

- name: "Install go"
  ansible.builtin.import_tasks: go.yml

- name: "Install terraform"
  ansible.builtin.import_tasks: terraform.yml

- name: "Install fzf"
  ansible.builtin.import_tasks: fzf.yml

- name: "Install neovim"
  ansible.builtin.import_tasks: neovim.yml

- name: "Install Visual Studio Code"
  ansible.builtin.import_tasks: visual_studio_code.yml
