---
- name: "Install neovim"
  become: true
  ansible.builtin.package:
    name:
      - neovim
      - ripgrep

# For some bizarre reason fedora requires this specific library
- name: "Install C++ 11 (Fedora)"
  become: true
  ansible.builtin.dnf:
    name:
      - libstdc++-static
      - gcc-c++

# ansible-lint is not currently available through Mason
- name: "Install ansible-lint (Fedora)"
  become: true
  ansible.builtin.dnf:
    name: python3-ansible-lint

- name: "Install LuaRocks (Fedora)"
  become: true
  ansible.builtin.dnf:
    name:
      - lua
      - lua-devel
      - cmake
      - luarocks

- name: "Clone neovim configuration"
  vars:
    repo:
      ssh: git@github.com:nicolomaioli/nvim.git
      https: https://github.com/nicolomaioli/nvim.git
  ansible.builtin.git:
    repo: "{{ repo[git['protocol']] }}"
    dest: "{{ ansible_user_dir }}/.config/nvim"
    version: main
    update: yes

- name: "Setup zsh (neovim)"
  ansible.builtin.lineinfile:
    name: "{{ ansible_user_dir }}/.zshenv"
    line: "export EDITOR=nvim"
    state: present
