---
- name: "Install python3"
  become: true
  ansible.builtin.package:
    name:
    - python3
    - python3-pip

- name: "Setup zsh (python3)"
  ansible.builtin.lineinfile:
    name: "{{ ansible_user_dir }}/.zshrc"
    line: 'export PATH="$HOME/.local/bin:$PATH"'
    state: present
