---
- name: "Install tmux"
  become: true
  ansible.builtin.package:
    name: tmux

- name: "Clone tpm"
  ansible.builtin.git:
    repo: https://github.com/tmux-plugins/tpm.git
    dest: "{{ ansible_user_dir }}/.tmux/plugins/tpm"
    version: master
    update: yes

- name: "Clone tmux configuration"
  vars:
    repo:
      ssh: git@github.com:nicolomaioli/tmux.git
      https: https://github.com/nicolomaioli/tmux.git
  ansible.builtin.git:
    repo: "{{ repo[git['protocol']] }}"
    dest: "{{ ansible_user_dir }}/.config/tmux"
    version: main
    update: yes

- name: "Setup zsh (tmux)"
  ansible.builtin.lineinfile:
    name: "{{ ansible_user_dir }}/.zshrc"
    line: '[ -f "$HOME/.config/tmux/workflow.zsh" ] && source "$HOME/.config/tmux/workflow.zsh"'
    state: present
