---
- name: "Configuration for X11"
  become: true
  ansible.builtin.package:
    name:
      - xinit
      - brightnessctl

- name: "Copy Intel graphics configs"
  become: true
  ansible.builtin.copy:
    src: "20-intel.conf"
    dest: "/etc/X11/xorg.conf.d/20-intel.conf"
    mode: "0644"

- name: "Copy touchpad configs"
  become: true
  ansible.builtin.copy:
    src: "30-touchpad.conf"
    dest: "/etc/X11/xorg.conf.d/30-touchpad.conf"
    mode: "0644"

- name: "Setup keyboard"
  when: true
  ansible.builtin.command:
    cmd: 'localectl set-x11-keymap "gb,us" "" "" "caps:ctrl_modifier,grp:alt_space_toggle"'
