---
- name: "Install zsh"
  become: true
  ansible.builtin.package:
    name:
      - zsh

- name: "Set zsh as the default shell"
  become: true
  ansible.builtin.user:
    name: "{{ ansible_user_id }}"
    shell: /bin/zsh

- name: "Install oh-my-zsh"
  ansible.builtin.git:
    repo: "https://github.com/robbyrussell/oh-my-zsh"
    dest: "{{ ansible_user_dir }}/.oh-my-zsh"
    version: master
    update: true

- name: "Copy .zshrc"
  ansible.builtin.copy:
    src: .zshrc
    dest: "{{ ansible_user_dir }}/.zshrc"
    mode: 0644
